INSERT INTO titulos (
id,titulo,descripcion,lanzamiento,genero,precio,publisher,imagen

)

VALUES ('1','S.T.A.L.K.E.R. 2: Heart of Chornobyl','Descubre la Zona de exclusión de Chornóbil, llena de enemigos peligrosos, anomalías letales y artefactos poderosos. Descubre tu propia historia épica y ábrete camino al Corazón de Chornóbil. Elige sabiamente, pues tus decisiones determinarán tu destino.','2024-11-20','Acción','10000.00','Naughty Dog LLC','/juegos_img/stalker_2.jpg'),
('2','HELLDIVERS 2','La última línea ofensiva de la galaxia. Enlístate en los Helldivers y únete a la lucha por la libertad en una galaxia hostil en este juego de disparos en tercera persona frenético y feroz','2024-02-08','Acción','95000.55','Play Station','/juegos_img/helldivers_2.jpg'),
('3','EA SPORTS FC 25','EA SPORTS FC™ 25 te ofrece más formas de ganar para el club. Forma equipo con amistades en tus modos favoritos con el nuevo Rush 5 vs. 5 y lidera a tu club hacia la victoria gracias a FC IQ, que te ofrece más control táctico que nunca.','2024-09-27','Deportes','50000.00','Electronic Arts','/juegos_img/fifa25.jpg'),
('4','Grand Theft Auto V','Grand Theft Auto V para PC ofrece a los jugadores la opción de explorar el galardonado mundo de Los Santos y el condado de Blaine con una resolución de 4K y disfrutar del juego a 60 fotogramas por segundo','2015-04-14','Acción','15000.58','Rockstar Games','/juegos_img/gta5.jpg'),
('5','Counter-Strike 2','Durante más de dos décadas, Counter-Strike ha brindado una experiencia competitiva de élite, una experiencia moldeada por millones de jugadores en todo el mundo. Ahora es el momento de comenzar el siguiente capítulo en la historia de CS. Esto es Counter-Strike 2.','2012-08-21','Acción','0.00','VALVE','/juegos_img/cs2.jpg'),
('6','Dota 2','Cada día, millones de jugadores de todo el mundo entran en batalla como uno de los más de cien héroes de Dota. Y no importa si es su décima o su milésima hora de juego: siempre hay algo nuevo que descubrir.','2013-07-09','Free to play','0.00','VALVE','/juegos_img/dota2.jpg'),
('7','Call of Duty: Black Ops 6','Call of Duty®: Black Ops 6 presenta la característica Campaña cinematográfica de Black Ops, la mejor experiencia de Multijugador y el épico regreso de Zomis pos rondas.','2024-10-25','Acción','59888.10','Blizzard','/juegos_img/cod6.jpg'),
('8','Left 4 Dead 2','Ambientado en el apocalipsis zombi, Left 4 Dead 2 (L4D2) es la esperadísima secuela del galardonado Left 4 Dead, el juego cooperativo número 1 de 2008. Este FPS cooperativo de acción terrorífica lleva a tus amigos y a ti a través de ciudades, pantanos y cementerios del Profundo Sur de EE. UU','2009-11-17','Acción','0.00','VALVE','/juegos_img/lfd2.jpg'),
('9','Portal 2','¡La Iniciativa de Prueba Perpetua ha sido ampliada, permitiéndote ahora diseñar rompecabezas cooperativos para ti y tus amigos!','2011-04-19','Acción','10000.00','VALVE','/juegos_img/portal2.jpg'),
('10','Half-Life 2','1998. HALF-LIFE supone un impacto en la industria de juegos gracias a su combinación de acción frenética y narración continua y absorbente. El título debut de Valve fue galardonado con más de 50 premios, que sentaron las bases para que luego se convirtiera en El mejor juego para PC de la historia.','2004-11-16','Acción','1000.15','VALVE','/juegos_img/hl2.jpg'),
('11','Metal Slug: Awakening','Metal Slug: Awakening continúa la jugabilidad clásica amada por los fanáticos, con nuevas y emocionantes características como World Adventure, Team-up de 3 jugadores y desafíos Roguelike. ¡Únete a tus amigos en línea para enfrentarte a jefes poderosos en cualquier momento y en cualquier lugar!','2024-07-19','Aventura','0.00','HAOPLAY Limited','/juegos_img/metal_slug_aw.jpg'),
('12','Once Human','Once Human es un juego de supervivencia multijugador de mundo abierto ambientado en un extraño futuro postapocalíptico. Únete a tus amigos para enfrentarte a monstruosos enemigos, descubre conspiraciones secretas, compite por los recursos y construye tu propio territorio.','2024-07-09','Supervivencia','15000.58','Starry Studio','/juegos_img/once_human.jpg'),
('13','Spectre Divide','Spectre Divide es el shooter táctico 3v3 competitivo y que evoluciona en el género impulsado por Duality. Usa Duality para controlar dos cuerpos en tiempo real, permitiéndote defender dos sitios a la vez, cubrir tu propia cruz o incluso intercambiarte a ti mismo. Domina el tiroteo táctico y un arsenal de tecnología del futuro para alcanzar la infamia.','2024-09-03','Free to play','0.00','Mountaintop Studios','/juegos_img/spectre.jpg'),
('14','SILENT HILL 2','«Me llamo... Maria», dice la mujer, sonriendo. Su rostro, su voz... Es igual que ella.','2024-10-08','Aventura','95000.55','KONAMI','/juegos_img/shill2.jpg'),
('15','Dead Space','El clásico de terror de ciencia ficción, regresa con una nueva versión totalmente renovada para ofrecer una experiencia aún más inmersiva, con mejoras visuales, de sonido y de jugabilidad, además de mantenerse fiel a la emocionante visión del juego original.','2023-01-27','Aventura','95000.55','Electronic Arts','/juegos_img/dspace.jpg'),
('16','Resident Evil 4','La supervivencia es solo el comienzo. A seis años del desastre biológico en Raccoon City, Leon S. Kennedy, uno de los sobrevivientes, rastreó a la hija secuestrada del presidente hasta una aldea europea aislada, donde algo terrible le ha ocurrido a los lugareños.','2023-03-23','Acción','95000.55','Play Station','/juegos_img/revil4.jpg'),('17','Metro Exodus','Huye de las ruinas del Metro de Moscú y embárcate en un viaje épico que abarca todo el continente a través de la naturaleza post-apocalíptica rusa. Explora vastos niveles no lineales, piérdete en una experiencia inmersiva de supervivencia en un entorno sandbox y sigue una emocionante historia que abarca un año entero.','2019-02-14','Acción','59888.10','Deep Silver','/juegos_img/metroexodus.jpg'),
('18','Metro Awakening','Metro Awakening es una aventura basada en la historia creada para realidad virtual que combina exploración atmosférica, sigilo y combate en una experiencia inmersiva. Ponte tu máscara de gas, enfréntate a la radiación y aventúrate en las profundidades del Metro.','2024-11-07','Acción','37555.80','Deep Silver','/juegos_img/metroawakening.jpg'),('19','arming Simulator 25','Farming Simulator 25 te invita a unirte a la gratificante vida en la granja, ya sea en solitario o de forma cooperativa en el modo multijugador. ¡Esta es tu granja!','2024-11-12','Simuladores','10200.90','GIANTS Software GmbH','/juegos_img/farmingsimulator.jpg'),
('20','DayZ','¿Cuánto puedes sobrevivir en un mundo posapocalíptico? Una tierra invadida por zombis infectados, donde los sobrevivientes compiten por los recursos disponibles. ¿Forjarás alianzas con extraños? ¿O buscarás la soledad para evitar traiciones? Esto es DayZ. Esta es tu historia.','2018-12-13','Acción','520.50','Bohemia Interactive','/juegos_img/dayz.jpg'),
('21','Project Zomboid','Project Zomboid es lo último en supervivencia zombie. Solo o en MP: saqueas, construyes, creas, luchas, cultivas y pescas en una lucha por sobrevivir. Un conjunto de habilidades de juego de rol incondicionales, un mapa extenso, un entorno de pruebas enormemente personalizable y un lindo mapache tutorial esperan a los incautos. Entonces, ¿cómo vas a morir? Todo lo que necesitas es un bocado.','2013-11-08','Supervivencia','10090.58','The Indie Stone','/juegos_img/pzomboid.jpg'),
('22','Warhammer 40,000: Space Marine 2','Encarna la habilidad y la brutalidad sobrehumanas de un marine espacial. Usa habilidades mortales y armamento devastador para exterminar a los tiránidos. Defiende al Imperium y disfruta de acción en tercera persona en modo individual o multijugador.','2024-09-09','Acción','35000.10','Focus Entertainment','/juegos_img/space_marine2.jpg'),
('23','Delta Force','Delta Force, un FPS táctico gratuito, regresa como última parte de la clásica serie. Como estandarte del género durante los últimos 25 años, Delta Force regresa con un arsenal mejorado de armas, entornos impactantes y un mundo realmente dinámico.','2024-12-04','Acción','32000.90','TiMi Studio Group','/juegos_img/delta_force.jpg'),
('24','Dead Frontier 2','Survival Horror en línea en su forma más oscura. Como uno de los pocos supervivientes del brote, debes vivir en las ruinas en descomposición de la sociedad.','2019-07-15','Supervivencia','10090.58','Creaky Corpse Ltd','/juegos_img/dead_frontier2.jpg'),
('25','The Last of Us Part I','Descubre el galardonado juego que inspiró la aclamada serie de televisión. Guía a Joel y Ellie en su travesía por una América posapocalíptica y encuentra aliados y enemigos inolvidables en The Last of Us.','2023-03-28','Acción','10090.58','Creaky Corpse Ltd','/juegos_img/tlou2.jpg');